# Generated by Django 6.0.6 on 2026-06-10 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('categoria', models.CharField(choices=[('5K', '5K'), ('10K', '10K'), ('21K', '21K'), ('42K', '42K')], default='10K', max_length=10)),
                ('melhor_tempo', models.DurationField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_atleta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('nome_organizacao', models.CharField(max_length=120)),
                ('uf', models.CharField(max_length=2)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_organizador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cref', models.CharField(max_length=20, unique=True)),
                ('especialidade', models.CharField(blank=True, max_length=60)),
                ('qtd_atletas_max', models.PositiveIntegerField(default=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_treinador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
